### ISSUE TITLE
Build error - Java Release 

### ISSUE THREAD

**Issue by satishnavada** [google/keyczar#167]
There are no download links to download the keytool and other related jars and files.
I tried to build the Java Release on mac using  Apache Maven 3.3.3  on Mac Yosemite.

https://github.com/google/keyczar/releases/tag/Java_release_0.71g

But getting following build error:
Command tried: mvn -X package

Error: 
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.287 s
[INFO] Finished at: 2015-06-23T18:50:31+05:30
[INFO] Final Memory: 7M/123M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:buildnumber-maven-plugin:1.0:create (default) on project keyczar: Cannot get the branch information from the scm repository :
[ERROR] Exception while executing SCM command. UnsupportedOperationException
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:buildnumber-maven-plugin:1.0:create (default) on project keyczar: Cannot get the branch information from the scm repository : 
Exception while executing SCM command.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Cannot get the branch information from the scm repository : 
Exception while executing SCM command.
    at org.codehaus.mojo.build.CreateMojo.getScmBranch(CreateMojo.java:653)
    at org.codehaus.mojo.build.CreateMojo.execute(CreateMojo.java:464)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    ... 20 more
Caused by: org.apache.maven.scm.ScmException: Exception while executing SCM command.
    at org.apache.maven.scm.command.AbstractCommand.execute(AbstractCommand.java:63)
    at org.apache.maven.scm.provider.git.AbstractGitScmProvider.executeCommand(AbstractGitScmProvider.java:290)
    at org.apache.maven.scm.provider.git.AbstractGitScmProvider.info(AbstractGitScmProvider.java:311)
    at org.codehaus.mojo.build.CreateMojo.info(CreateMojo.java:747)
    at org.codehaus.mojo.build.CreateMojo.getScmBranch(CreateMojo.java:620)
    ... 23 more
Caused by: java.lang.UnsupportedOperationException
    at org.apache.maven.scm.provider.git.gitexe.command.info.GitInfoCommand.executeCommand(GitInfoCommand.java:56)
    at org.apache.maven.scm.command.AbstractCommand.execute(AbstractCommand.java:59)
    ... 27 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by akadaedalus** [comment]
I came across this issue myself.  Key error:

```
org.codehaus.mojo:buildnumber-maven-plugin:1.0:create (default) on project keyczar: Cannot get the branch information from the scm repository : 
```

The maven plugin `buildnumber-maven-plugin` expects there to be a branch from git, subversion, or mercurial.  I worked around it by cloning the repository and compiling from that.

**Comment by markbridge1** [comment]
Same thing - deleted the buildnumber-maven-plugin entry and references to -${buildNumber} in the pom
