### ISSUE TITLE
Can't add key to keyset that doesn't have name.

### ISSUE THREAD

**Issue by devinrsmith** [google/keyczar#180]
`java -jar /Users/dsmith/.m2/repository/org/keyczar/keyczar/0.71g/keyczar-0.71g-shaded.jar addkey --location=/Users/dsmith/test2 --status=primary`

```
java.lang.RuntimeException: org.json.JSONException: JSONObject["name"] not found.
        at org.keyczar.KeyMetadata.read(KeyMetadata.java:204)
        at org.keyczar.Keyczar.<init>(Keyczar.java:79)
        at org.keyczar.GenericKeyczar.<init>(GenericKeyczar.java:28)
        at org.keyczar.KeyczarTool.createGenericKeyczar(KeyczarTool.java:520)
        at org.keyczar.KeyczarTool.addKey(KeyczarTool.java:288)
        at org.keyczar.KeyczarTool.main(KeyczarTool.java:130)
Caused by: org.json.JSONException: JSONObject["name"] not found.
        at org.json.JSONObject.get(JSONObject.java:499)
        at org.json.JSONObject.getString(JSONObject.java:670)
        at org.keyczar.KeyMetadata.read(KeyMetadata.java:194)
        ... 5 more
```

Fixed by ensuring the keyset I created has a name.

**Comment by Jessevanbekkum** [comment]
I had the same issue. The --name command in create is not optional, even though the documentation says so
