### ISSUE TITLE
testParseX509 fails for python-keyczar using pyasn1 0.2.x

### ISSUE THREAD

**Issue by toddrme2178** [google/keyczar#209]
When building python-keyczar on openSUSE we are getting the following build error when using pyasn1 0.2.1, 0.2.2, and 0.2.3.  It does not occur with pyasn1 0.1.9. It occurs in both python-keyczar 0.715 and 0.716.

```
pushd tests/keyczar_tests
python alltests.py
............................................................................E..
======================================================================
ERROR: testParseX509 (util_test.ParseX509Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/abuild/rpmbuild/BUILD/python-keyczar-0.716/tests/keyczar_tests/util_test.py", line 97, in testParseX509
    params = util.ParseX509(publickey)
  File "/home/abuild/rpmbuild/BUILDROOT/python-python-keyczar-0.716-27.1.x86_64/usr/lib/python2.7/site-packages/keyczar/util.py", line 176, in ParseX509
    prettyPrint()[2:-3])))[0]
  File "/usr/lib/python2.7/site-packages/pyasn1/codec/ber/decoder.py", line 717, in __call__
    raise error.PyAsn1Error('Zero tag encountered')
PyAsn1Error: Zero tag encountered

----------------------------------------------------------------------
Ran 79 tests in 3.788s

FAILED (errors=1)
error: Bad exit status from /var/tmp/rpm-tmp.GpLurC (%check)
```

**Comment by sebix** [comment]
I am just packaging this version and will ignore this test now as it seems it's not very important - based on the feedback to this bugreport.
